---
- name: "Install ca-certificates package"
  yum:  name=ca-certificates state=present

- name: "Check CA Trust Expansion state"
  command: "/usr/bin/update-ca-trust check"
  always_run: true
  changed_when: false
  register: result

- name: "Set CA Trust fact"
  set_fact:
    ca_trust_expanded: "{{ result.stdout.find( 'PEM/JAVA Status: ENABLED.') != -1 }}"

- name: "Enable CA Trust Expansion"
  command: update-ca-trust enable
  when: not ca_trust_expanded
