---
- name: Install trusted CA Certificates
  copy:
    content: "{{ item.pem }}"
    dest: "{{ ca_certificates_local_dir }}/{{ item.name }}.crt"
    group: root
    mode: '0644'
    owner: root
  with_items: "{{ ca_certificates_trusted }}"
  loop_control:
    label: "{{ item.name }}"
  register: _ca_certificates_copied
  notify: update ca-certificates
