---

- name: Load OS Family specific defaults
  include_vars: "defaults-{{ ansible_os_family }}.yml"

- name: Debian Family
  include: ca_certificates-Debian.yml
  when: ansible_os_family == 'Debian'

- name: RedHat Family
  include: ca_certificates-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Install Trusted
  include: ca_certificates-trusted.yml
