---

- name: Load OS Family specific defaults
  include_vars: "defaults-{{ ansible_os_family }}.yml"

- name: Debian Family
  include: ca_certificates-Debian.yml
  when: ansible_os_family == 'Debian'

- name: RedHat Family
  include: ca_certificates-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Install Trusted (Ansible < 2.2)
  include: ca_certificates-trusted-lt-2.2.yml
  static: false
  when: ansible_version['full'] | version_compare('2.2.0.0', operator='lt')

- name: Install Trusted (Ansible >= 2.2)
  include: ca_certificates-trusted-ge-2.2.yml
  static: false
  when: ansible_version['full'] | version_compare('2.2.0.0', operator='ge')
