---
- name: update ca-certificates (Debian)
  command: /usr/sbin/update-ca-certificates
  when: ansible_os_family == 'Debian'

- name: update ca-certificates (RedHat)
  command: /usr/bin/update-ca-trust
  when: ansible_os_family == 'RedHat'
