---
- name: ca-certificates update (Debian)
  command: /usr/sbin/update-ca-certificates
  when: ansible_os_family == 'Debian'

- name: ca-certificates update (RedHat)
  command: /usr/bin/update-ca-trust
  when: ansible_os_family == 'RedHat'
